layout_spectrum: 0.2056928
color:
  saturation: 1
  brandStrength: 0.7384141
  lightness: 0.2056928
  rhythmicContrast: 0.5042965
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.4957035
name: miamarzan
